Move most things to es6 imports (smh mongodb) and clean up some code.
Zordlan/SkyClientBot pull request #16
Opened 2021-06-03 16:14 UTC by vooxal

2021-06-03 16:16 UTC, vooxal commented
also side note: why
```js
function name(){
    //code goes here
}
```
and not modern syntax
```js
const name = () => {
    //code goes here
}
```

2021-06-04 05:10 UTC, TymanWasTaken requested changes

2021-06-04 05:10 UTC, TymanWasTaken commented on src/functions/database.ts
> +import 'dotenv/config';
This can be swapped for a command line flag iirc

2021-06-04 05:10 UTC, TymanWasTaken commented on src/functions/database.ts
>          await mongoclient.connect().then(() => {
this could probably be changed to
```ts
await mongoclient.connect()
const database = mongoclient.dv('bot')
```

2021-06-04 05:12 UTC, Zordlan commented on src/functions/database.ts
> +const uri = process.env.mongodb;
ngl i never knew you could do this

2021-06-04 05:13 UTC, merged

2021-06-04 20:44 UTC, vooxal commented on src/functions/database.ts
> +const uri = process.env.mongodb;
Yeah, since process.env is a object, you can reference with `[ ]` or `.`. usually you use `[ ]` when you want to put a variable there like
```js
const i = "mongodb"
process.env[i];
```
but when you use a string you can just use `.`